27 add and remove bin markers on googlemaps
SDP-BeGreen/BeGreen pull request #64
Opened 2023-04-19 19:14 UTC by iliasmerigh

### **In this pull PR I did the following :**

- Added a fake bins database with its tests
- Once the googlemaps fragment is launched it displays all bins with a marker
- When we click on a marker it deletes the bin marker
- When we click somewhere in the map it creates a new bin in that place
- There are various types of bin : plastic, paper etc... Each one is associated to a color so we can distinguish them in the map.

### **Encountered issues** :

- The bootcamp itself says that the googlemaps API is difficult to test so I didn't manage to fully test it. However I wrote some trivial test that allows the app to crash if something is wrong. At first, this test seems useless but it helped me a lot by crashing the app when there were some bugs.

- The bins creation modification is very long so I decided to focus on the main features that were associated in my issue. In a later spint, I will try to :
• Let the user add custom bin types (for now it automatically selects an arbitrary type)
• Remove a bin in another way than just clicking on its marker
• Add a bin in another way than just click on the map
• The user should not be able to create a bin far away from its current location
... and maybe some other features

2023-04-20 20:06 UTC, LucaCarroz requested changes
Good addings overall!
Just a few comments made: concerning the use of methods in FirebaseDB, it might be too late to refactor the code to use those methods, but remember the existence of those methods when you store the bin locations on the actual database :)

2023-04-20 20:06 UTC, LucaCarroz commented on app/src/main/java/com/github/sdp_begreen/begreen/fragments/MapFragment.kt
> +            val bin = Bin(0, BinType.PLASTIC, userLocation!!.latitude, userLocation!!.latitude)
```suggestion
            val bin = Bin(0, BinType.PLASTIC, userLocation!!.latitude, userLocation!!.longitude)
```
I think there's a little typo here

2023-04-21 06:09 UTC, LucaCarroz approved these changes
Seems good to me!

2023-04-21 06:23 UTC, merged

2023-04-23 15:53 UTC, AlSchlo commented on app/src/main/java/com/github/sdp_begreen/begreen/models/Bin.kt
> +class Bin(val id: Int, val type: BinType, val lat : Double, val long : Double) {
This can be a data class