Refacotre MeetingServices into EventServices
SDP-BeGreen/BeGreen pull request #93
Opened 2023-05-10 12:31 UTC by david-schroeter

2023-05-10 20:09 UTC, LucaCarroz requested changes
Excellent refactor and addings, that will make adding contests much more easier!
Since this PR mainly refactors already existing code, I do not have much comments (just a few comments that you forgot to change when you refactored).
Thanks a lot David!

2023-05-11 06:45 UTC, david-schroeter commented on app/src/main/java/com/github/sdp_begreen/begreen/utils/CopyableWithId.kt
> +    fun copy(newId: String): T
Yes you are absolutely right! What do you think of `copyWithNewId`. So that it stays in the theme with `copyableWithId` ?

2023-05-11 07:03 UTC, david-schroeter commented on firebase_emulator_data/firebase-export-metadata.json
Well seen, I updated my `firebase` instance and re-exported the data to use the last version.

2023-05-11 07:10 UTC, david-schroeter commented on app/src/test/java/com/github/sdp_begreen/begreen/models/event/ContestTest.kt
> +
I noticed that as well, and didn't really know why. I will add your suggested tests. Hopefully it works!

2023-05-11 11:01 UTC, LucaCarroz commented on app/src/main/java/com/github/sdp_begreen/begreen/utils/CopyableWithId.kt
> +    fun copy(newId: String): T
Sounds good, thanks for the changes!

2023-05-11 11:03 UTC, LucaCarroz approved these changes
Thanks for the changes! Looks good to me now

2023-05-11 11:05 UTC, merged